services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'postgres_auth'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - auth_network
    volumes:
      - auth_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: 'auth_service'
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      - auth_network
    depends_on:
      - postgres

networks:
  auth_network:

volumes:
  auth_data: